# Generated by Django 4.0.3 on 2022-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_character_comment_genre_useruniquetoken_person_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', through='movie_app.Character', to='movie_app.person', verbose_name='Aktorzy'),
        ),
    ]
